title: Fiction International
# change baseurl to "" for serve and "." for build
baseurl: ""
url: ""

collections:
  issues:
    output: true
    # sort_by: num

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
  - scope:
      path: ""
    values:
      layout: "default"