title: Fiction International
# baseurl: "C:/Users/Justin/Documents/GitHub/fiction-international/_site" # for local build
baseurl: "." # for hosting and serving
url: ""
markdown: kramdown
include: [_data]

collections:
  issues:
    output: true
    sort_by: num
    permalink: /issues/:name

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
  - scope:
      path: ""
    values:
      layout: "default"