title: Fiction International
# change baseurl to "" for serve and "." for build
baseurl: "."
url: ""
markdown: kramdown
include: [_data]

collections:
  issues:
    output: true
    sort_by: num
    permalink: /issues/:name

defaults:
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
  - scope:
      path: ""
    values:
      layout: "default"